name: Build JRuby

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      BUNDLE_GEMFILE: gemfiles/jruby.gemfile
      CI: true
    strategy:
      fail-fast: false
      matrix:
        ruby: ["jruby-9.4"]
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run RSpec
      run: |
        bundle exec rspec
